# This is a basic workflow to help you get started with Actions
name: Azure Bicep Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "main" ] #you could use "master", but "main" is what works best

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Echo Script
        run: echo Starting Bicep...

      # # Runs a set of commands using the runners shell
      # - name: Login with Azure
      #   uses: azure/login@v1
      #   with:
      #     creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: Azure Login with Managed Identity
        uses: azure/login@v2
        with:
          auth-type: IDENTITY
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          # Include client-id if you're using a user-assigned identit
          #client-id: ${{ secrets.AZURE_CLIENT_ID }}
          enable-AzPSSession: true


      # Deploys bicep script
      - name: Deploy the Bicep Script
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: "GenAItrial" #change to reflect your Resource Group
          template: azure-resources.bicep